?start: (rule | delegation)+

rule: "RULE" action "IF" condition

// Akcja
action: ALLOW_KW | DENY_KW
ALLOW_KW: "ALLOW"
DENY_KW: "DENY"

// Operatory logiczne
?condition: and_operator
?and_operator: or_operator ("AND" or_operator)*
?or_operator: atom ("OR" atom)*
?atom: comparison
    | "(" condition ")"
comparison: attribute op value | attribute op attribute

// Atrybuty
attribute: WORD "." WORD

// Operatory
op: EQUAL_OP | NOT_EQUAL_OP | GREATER_THAN_OR_EQUAL_OP | GREATER_THAN_OP | LESSER_THAN_OR_EQUAL_OP | LESSER_THAN_OP
EQUAL_OP: "=="
NOT_EQUAL_OP: "!="
GREATER_THAN_OP: ">"
GREATER_THAN_OR_EQUAL_OP: ">="
LESSER_THAN_OP: "<"
LESSER_THAN_OR_EQUAL_OP: "<="

// Delegacja
delegation: "DELEGATION" "{" parameter+ "}"
parameter: key ":" (condition | array | value)
key: WORD

// Pozostale
value: WORD | NUMBER | ESCAPED_STRING
array: "[" [value ("," value)*] "]"
WORD: /[a-zA-Z_][a-zA-Z0-9_]*/

// Komentarz
COMMENT: /#[^\n]*/

// Nakaz ignorowania komentarzy przez parser
%ignore COMMENT

// Importy
%import common.ESCAPED_STRING
%import common.NUMBER
%import common.WS
%ignore WS
