FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY ../common/ /app/common/

RUN pip install --no-cache-dir -r requirements.txt

COPY PIP /app
EXPOSE 8000

WORKDIR /app
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]